name: CVE漏洞监控系统

on:
  schedule:
    # 每15分钟执行一次数据拉取
    - cron: '*/15 * * * *'
    # 每天10:00执行邮件发送
    - cron: '0 10 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  run_monitor:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests feedparser python-dotenv
      
      - name: 恢复JSON数据文件
        uses: actions/cache@v3
        with:
          path: cve_vulnerabilities.json
          key: cve-data-json-cache
      
      - name: 执行数据拉取或邮件发送
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          # 根据触发时间判断执行模式
          RUN_MODE: ${{ github.event.schedule == '0 10 * * *' && 'send_email' || 'fetch_data' }}
        run: |
          python cve-rss.py
      
      - name: 提交更新的数据文件
        if: env.RUN_MODE == 'fetch_data'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add cve_vulnerabilities.json
          git commit -m "Update CVE data: $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
